app_settings:
  abilities:
    - name: sandbox
      is_enabled: true
      is_root: true
      ability_type: InterfaceBackend 
    - name: butlers
      is_enabled: true
      is_root: false
      ability_type: InterfaceBackend
  api_keys:
    open_ai: 'sk-ss'
    anthropic: 'an-sss'
    local: 'loc-lc'
    custom_api: 'cus-ap'